name: gowaslu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  bubble_bottom_bar: ^2.0.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  floating_bottom_navigation_bar: ^1.5.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/

